### PR TITLE
Href bug fix

### PR DESCRIPTION
**Pull request by icbat**
The bookmarklet runs on the history tab because it technically matched the trades page and had a help section.

### CODE REVIEW

**Comment by icbat** [comment]
I didn't update the gh-pages branch or the CHANGES.MD as it looks like you push out updates in batches =) Happy to do that too if you'd like.

**Comment by llamasoft** [comment]
Good find, but I'm not certain that the pull request fixes the issue.  The URL checking validates that the URL contains the specified strings, of which the history page (pucatrade.com/trades/past/sent) still matches.

Maybe I'm misreading the pull request?

**Comment by icbat** [comment]
It's been a while but I think this did actually work. I'll take another look and at least make it obvious what it's doing. JavaScript is still new to me but I'm learning at work now, too.

**Comment by icbat** [comment]
Does that help clear it up? The "send" page cannot have a trailing `/` in it; if you try to navigate there it redirects you and strips the `/`. So you're looking for `pucatrade.com/trades` but not `pucatrade.com/trades/`

**Comment by icbat** [comment]
How are we looking here? Anything I can do to move this along? There's a bigger PR I'd like to make that relies on this fix :-)

**Comment by llamasoft** [comment]
Fixed in newest push.  Sorry for the wait!

**Pull request closed without merging**
