### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by Kerrick**
I'd love to start contributing to PucaPower, but there's no clear license. This PR adds the MIT license so people can develop and contribute without worry.

### CODE REVIEW

**Comment by icbat** [comment]
:+1:

**Comment by llamasoft** [comment]
I've been meaning to add a license for a while now.  I'm still shopping around to see which one fits best.  I'll add one as soon as I've made up my mind, but I will keep your suggestion in consideration.

**Comment by Kerrick** [comment]
Any news on this? I'd love to contribute and add support for HTML5 notifications. :)

**Comment by llamasoft** [comment]
Alright!  Lets do this!

**Comment by icbat** [comment]
Wooo!

**Pull request merged**
